[package]
name = "localscale-agent"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "agent/protocol", "control-plane", "agent/protocol/agent/transport"]

[dependencies]
localscale-control-plane = { path = "control-plane" }
localscale-agent-protocol = { path = "agent/protocol" }
localscale-agent-transport = { path = "agent/protocol/agent/transport" }

[lib]
name = "localscale_agent"
path = "src/lib.rs"

[[bin]]
name = "localscaled"
path = "src/main.rs"
