//! Self-contained Tor runtime support.
//!
//! This module intentionally has no PATH lookup and no dependency on a system
//! `tor`, `torsocks`, or `arti` installation. The executable must be shipped
//! beside the LocalScale application bundle.

use std::fs::{self, OpenOptions};
use std::io::{self, BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::mpsc::{self, Receiver};
use std::time::{Duration, Instant};

const MAX_LOG_BYTES: usize = 64 * 1024;

#[derive(Debug)]
pub enum TorRuntimeError {
    Io(io::Error),
    MissingBundledExecutable { searched: Vec<PathBuf> },
    UnsafeBundledExecutable(PathBuf),
    InvalidHostname(String),
    InsecureDataDirectory(PathBuf),
    InvalidConfig(String),
    Exited(ExitStatus),
    ReadinessTimeout,
    ReadinessFailed(String),
}

impl std::fmt::Display for TorRuntimeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "Tor runtime I/O error: {e}"),
            Self::MissingBundledExecutable { searched } => write!(f, "bundled Tor executable not found in: {searched:?}"),
            Self::UnsafeBundledExecutable(path) => write!(f, "bundled Tor executable is unsafe: {}", path.display()),
            Self::InvalidHostname(host) => write!(f, "invalid Tor v3 hostname: {host}"),
            Self::InsecureDataDirectory(path) => write!(f, "Tor data directory is not private: {}", path.display()),
            Self::InvalidConfig(message) => write!(f, "invalid Tor configuration: {message}"),
            Self::Exited(status) => write!(f, "bundled Tor exited before readiness: {status}"),
            Self::ReadinessTimeout => f.write_str("bundled Tor readiness timed out"),
            Self::ReadinessFailed(message) => write!(f, "bundled Tor readiness failed: {message}"),
        }
    }
}
impl std::error::Error for TorRuntimeError {}
impl From<io::Error> for TorRuntimeError { fn from(e: io::Error) -> Self { Self::Io(e) } }

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TorMode {
    Host { service_port: u16, upstream: String },
    Client { hostname: String },
}

impl TorMode {
    pub fn host(service_port: u16, upstream: impl Into<String>) -> Result<Self, TorRuntimeError> {
        let upstream = upstream.into();
        validate_upstream(&upstream)?;
        Ok(Self::Host { service_port, upstream })
    }
    pub fn client(hostname: impl Into<String>) -> Result<Self, TorRuntimeError> {
        let hostname = hostname.into();
        validate_v3_hostname(&hostname)?;
        Ok(Self::Client { hostname })
    }
}

/// Validate the exact lowercase 56-character base32 form used by Tor v3.
pub fn validate_v3_hostname(hostname: &str) -> Result<(), TorRuntimeError> {
    let Some(label) = hostname.strip_suffix(".onion") else { return Err(TorRuntimeError::InvalidHostname(hostname.into())); };
    if label.len() != 56 || !label.bytes().all(|b| matches!(b, b'a'..=b'z' | b'2'..=b'7')) {
        return Err(TorRuntimeError::InvalidHostname(hostname.into()));
    }
    Ok(())
}

/// Validate the hostname at the point it is obtained/configured for either mode.
/// A Host hostname is generated by Tor; a Client hostname comes from config.
pub fn validate_hostname_for_mode(mode: &TorMode, hostname: &str) -> Result<(), TorRuntimeError> {
    match mode {
        TorMode::Host { .. } | TorMode::Client { .. } => validate_v3_hostname(hostname),
    }
}

pub fn validate_host_generated_hostname(hostname: &str) -> Result<(), TorRuntimeError> {
    validate_v3_hostname(hostname)
}

/// Resolve only a shipped executable. This function never searches PATH.
pub fn resolve_bundled_tor(bundle_root: &Path) -> Result<PathBuf, TorRuntimeError> {
    let candidates = if cfg!(target_os = "linux") {
        vec![bundle_root.join("tor").join("tor")]
    } else if cfg!(target_os = "macos") {
        vec![bundle_root.join("Contents/Resources/tor/tor"), bundle_root.join("tor/tor")]
    } else if cfg!(target_os = "windows") {
        vec![bundle_root.join("tor").join("tor.exe")]
    } else {
        vec![bundle_root.join("tor").join("tor")]
    };
    for path in &candidates {
        let metadata = match fs::symlink_metadata(path) { Ok(m) => m, Err(_) => continue };
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            return Err(TorRuntimeError::UnsafeBundledExecutable(path.clone()));
        }
        #[cfg(unix)]
        if metadata.permissions().mode() & 0o111 == 0 {
            return Err(TorRuntimeError::UnsafeBundledExecutable(path.clone()));
        }
        return Ok(path.clone());
    }
    Err(TorRuntimeError::MissingBundledExecutable { searched: candidates })
}

/// Resolve relative to the installed executable, not the current directory or PATH.
pub fn resolve_installed_bundled_tor() -> Result<PathBuf, TorRuntimeError> {
    let executable = std::env::current_exe()?;
    resolve_bundled_tor(executable.parent().ok_or_else(|| io::Error::other("executable has no parent"))?)
}

/// Create or validate a LocalScale-owned private runtime directory.
pub fn prepare_data_directory(path: &Path) -> Result<(), TorRuntimeError> {
    if path.exists() {
        if !path.is_dir() { return Err(TorRuntimeError::InsecureDataDirectory(path.into())); }
        enforce_private_mode(path)?;
    } else {
        fs::create_dir_all(path)?;
        set_private_mode(path)?;
        enforce_private_mode(path)?;
    }
    Ok(())
}

#[cfg(unix)]
fn set_private_mode(path: &Path) -> io::Result<()> { use std::os::unix::fs::PermissionsExt; fs::set_permissions(path, fs::Permissions::from_mode(0o700)) }
#[cfg(not(unix))]
fn set_private_mode(_path: &Path) -> io::Result<()> { Ok(()) }
#[cfg(unix)]
fn enforce_private_mode(path: &Path) -> Result<(), TorRuntimeError> { use std::os::unix::fs::PermissionsExt; if fs::metadata(path)?.permissions().mode() & 0o077 != 0 { return Err(TorRuntimeError::InsecureDataDirectory(path.into())); } Ok(()) }
#[cfg(not(unix))]
fn enforce_private_mode(_path: &Path) -> Result<(), TorRuntimeError> { Ok(()) }

#[derive(Debug)]
pub struct TorRuntime {
    executable: PathBuf,
    data_dir: PathBuf,
    torrc: PathBuf,
}

impl TorRuntime {
    pub fn new(executable: PathBuf, data_dir: PathBuf) -> Result<Self, TorRuntimeError> {
        let metadata = fs::symlink_metadata(&executable).map_err(TorRuntimeError::Io)?;
        if executable.is_relative() || metadata.file_type().is_symlink() || !metadata.is_file() { return Err(TorRuntimeError::UnsafeBundledExecutable(executable)); }
        prepare_data_directory(&data_dir)?;
        let torrc = data_dir.join("torrc");
        Ok(Self { executable, data_dir, torrc })
    }

    pub fn write_torrc(&self, mode: &TorMode) -> Result<&Path, TorRuntimeError> {
        let content = render_torrc(&self.data_dir, mode)?;
        let mut options = OpenOptions::new();
        options.write(true).create(true).truncate(true);
        #[cfg(unix)] options.mode(0o600);
        let mut file = options.open(&self.torrc)?;
        file.write_all(content.as_bytes())?;
        file.sync_all()?;
        #[cfg(unix)] { use std::os::unix::fs::PermissionsExt; fs::set_permissions(&self.torrc, fs::Permissions::from_mode(0o600))?; }
        Ok(&self.torrc)
    }

    /// Read and validate Tor's generated Host v3 hostname without exposing key material.
    pub fn generated_host_hostname(&self) -> Result<String, TorRuntimeError> {
        let path = self.data_dir.join("hidden_service").join("hostname");
        let contents = fs::read_to_string(path)?;
        let mut lines = contents.lines();
        let hostname = lines.next().unwrap_or("").trim();
        if hostname.is_empty() || lines.next().is_some() {
            return Err(TorRuntimeError::InvalidHostname(hostname.into()));
        }
        validate_host_generated_hostname(hostname)?;
        Ok(hostname.to_owned())
    }

    /// Spawn exactly the resolved bundled executable with the generated torrc.
    pub fn spawn(&self, mode: &TorMode) -> Result<TorProcess, TorRuntimeError> {
        self.write_torrc(mode)?;
        let mut child = Command::new(&self.executable)
            .arg("-f").arg(&self.torrc)
            .env_clear()
            .env("PATH", "")
            .stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::piped())
            .spawn()?;
        let stderr = child.stderr.take().ok_or_else(|| io::Error::other("Tor stderr pipe was not created"))?;
        let (sender, readiness) = mpsc::channel();
        std::thread::spawn(move || {
            for line in BufReader::new(stderr).lines().map_while(Result::ok) {
                let _ = sender.send(line);
            }
        });
        Ok(TorProcess { child, readiness })
    }
}

pub fn render_torrc(data_dir: &Path, mode: &TorMode) -> Result<String, TorRuntimeError> {
    if data_dir.is_relative() { return Err(TorRuntimeError::InvalidConfig("data directory must be absolute".into())); }
    let mut config = format!("DataDirectory {}\nSocksPort 127.0.0.1:0\n", data_dir.display());
    match mode {
        TorMode::Host { service_port, upstream } => {
            validate_upstream(upstream)?;
            config.push_str(&format!("ClientOnly 0\nHiddenServiceDir {}\nHiddenServiceVersion 3\nHiddenServicePort {} {}\n", data_dir.join("hidden_service").display(), service_port, upstream));
        }
        TorMode::Client { hostname } => { validate_v3_hostname(hostname)?; config.push_str("ClientOnly 1\n"); }
    }
    Ok(config)
}

fn validate_upstream(upstream: &str) -> Result<(), TorRuntimeError> {
    let (host, port) = upstream.rsplit_once(':').ok_or_else(|| TorRuntimeError::InvalidConfig("upstream must be host:port".into()))?;
    if host.is_empty() || port.parse::<u16>().is_err() || host.contains('/') || host.contains('\n') { return Err(TorRuntimeError::InvalidConfig("invalid upstream".into())); }
    Ok(())
}

#[derive(Debug)]
pub struct TorProcess { child: Child, readiness: Receiver<String> }
impl TorProcess {
    pub fn try_exit(&mut self) -> Result<Option<ExitStatus>, TorRuntimeError> { Ok(self.child.try_wait()?) }
    pub fn wait(&mut self) -> Result<ExitStatus, TorRuntimeError> { Ok(self.child.wait()?) }
    pub fn terminate(&mut self) -> Result<ExitStatus, TorRuntimeError> {
        if self.child.try_wait()?.is_none() {
            self.child.kill()?;
        }
        Ok(self.child.wait()?)
    }
    /// Wait for Tor's authenticated bootstrap completion without treating spawn as ready.
    pub fn wait_for_readiness(&mut self, timeout: Duration) -> Result<(), TorRuntimeError> {
        let deadline = Instant::now() + timeout;
        while Instant::now() < deadline {
            if let Some(status) = self.child.try_wait()? { return Err(TorRuntimeError::Exited(status)); }
            let remaining = deadline.saturating_duration_since(Instant::now());
            match self.readiness.recv_timeout(remaining.min(Duration::from_millis(100))) {
                Ok(line) if line.contains("Bootstrapped 100%") => return Ok(()),
                Ok(_) => {},
                Err(mpsc::RecvTimeoutError::Timeout) => {},
                Err(mpsc::RecvTimeoutError::Disconnected) => break,
            }
        }
        Err(TorRuntimeError::ReadinessTimeout)
    }
}

#[allow(dead_code)]
fn bounded_lines(receiver: Receiver<String>, deadline: Instant) -> String {
    let mut output = String::new();
    while Instant::now() < deadline {
        match receiver.recv_timeout(Duration::from_millis(25)) {
            Ok(line) => { output.push_str(&line); if output.len() > MAX_LOG_BYTES { output.truncate(MAX_LOG_BYTES); break; } }
            Err(mpsc::RecvTimeoutError::Timeout) => {}
            Err(_) => break,
        }
    }
    output
}

#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp(name: &str) -> PathBuf { std::env::temp_dir().join(format!("localscale-tor-{name}-{}", SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos())) }
    fn fake_tor(root: &Path) -> PathBuf { let path = root.join("tor/tor"); fs::create_dir_all(path.parent().unwrap()).unwrap(); fs::write(&path, b"not tor").unwrap(); #[cfg(unix)] fs::set_permissions(&path, fs::Permissions::from_mode(0o700)).unwrap(); path }
    fn valid() -> String { format!("{}.onion", "a".repeat(56)) }

    #[test] fn bundle_resolution_is_relative_and_never_path_based() { let root = temp("bundle"); let expected = fake_tor(&root); assert_eq!(resolve_bundled_tor(&root).unwrap(), expected); let _ = fs::remove_dir_all(root); }
    #[test] fn missing_bundle_rejects_system_path_fallback() { let root = temp("missing"); fs::create_dir_all(&root).unwrap(); assert!(matches!(resolve_bundled_tor(&root), Err(TorRuntimeError::MissingBundledExecutable { .. }))); let _ = fs::remove_dir_all(root); }
    #[test] fn torrc_isolated_to_data_directory() { let root = temp("config"); fs::create_dir_all(&root).unwrap(); let mode = TorMode::host(80, "127.0.0.1:8080").unwrap(); let text = render_torrc(&root, &mode).unwrap(); assert!(text.contains(&format!("DataDirectory {}", root.display()))); assert!(!text.contains("/etc/tor") && !text.contains("/var/lib/tor")); let _ = fs::remove_dir_all(root); }
    #[test] fn data_directory_is_restrictive() { let root = temp("private"); prepare_data_directory(&root).unwrap(); #[cfg(unix)] assert_eq!(fs::metadata(&root).unwrap().permissions().mode() & 0o777, 0o700); let _ = fs::remove_dir_all(root); }
    #[test] fn existing_insecure_directory_is_rejected() { let root = temp("insecure"); fs::create_dir_all(&root).unwrap(); #[cfg(unix)] fs::set_permissions(&root, fs::Permissions::from_mode(0o755)).unwrap(); #[cfg(unix)] assert!(matches!(prepare_data_directory(&root), Err(TorRuntimeError::InsecureDataDirectory(_)))); let _ = fs::remove_dir_all(root); }
    #[test] fn host_and_client_validate_v3_hostname() { assert!(validate_v3_hostname(&valid()).is_ok()); assert!(TorMode::client(valid()).is_ok()); assert!(validate_v3_hostname(&format!("{}.onion", "a".repeat(55))).is_err()); assert!(validate_v3_hostname(&format!("{}.onion", "A".repeat(56))).is_err()); }
}
